"""Core inference logic for Datasculpt."""

from datasculpt.core.grain import (
    KeyCandidate,
    calculate_confidence,
    calculate_uniqueness_ratio,
    has_stable_grain,
    infer_grain,
    rank_key_candidates,
    search_composite_keys,
    test_single_column_uniqueness,
)
from datasculpt.core.shapes import (
    ShapeResult,
    compare_hypotheses,
    detect_shape,
    generate_explanation,
    score_long_indicators,
    score_long_observations,
    score_series_column,
    score_wide_observations,
    score_wide_time_columns,
)
from datasculpt.core.time import (
    GranularityResult,
    ParsedTimeHeader,
    SeriesFrequencyResult,
    TimeGranularity,
    TimeRangeResult,
    detect_granularity,
    detect_granularity_from_name,
    detect_granularity_from_values,
    extract_time_range,
    extract_time_ranges,
    infer_series_frequency,
    parse_time_header,
    parse_time_headers,
)
from datasculpt.core.types import (
    ColumnEvidence,
    ColumnSpec,
    DatasetKind,
    DecisionRecord,
    GrainInference,
    HypothesisScore,
    InferenceConfig,
    InvariantProposal,
    PrimitiveType,
    Question,
    Role,
    ShapeHypothesis,
    StructuralType,
)

__all__ = [
    # Types
    "ColumnEvidence",
    "ColumnSpec",
    "DatasetKind",
    "DecisionRecord",
    "GrainInference",
    "HypothesisScore",
    "InferenceConfig",
    "InvariantProposal",
    "PrimitiveType",
    "Question",
    "Role",
    "ShapeHypothesis",
    "StructuralType",
    # Grain inference
    "KeyCandidate",
    "calculate_confidence",
    "calculate_uniqueness_ratio",
    "has_stable_grain",
    "infer_grain",
    "rank_key_candidates",
    "search_composite_keys",
    "test_single_column_uniqueness",
    # Shape detection
    "ShapeResult",
    "compare_hypotheses",
    "detect_shape",
    "generate_explanation",
    "score_long_indicators",
    "score_long_observations",
    "score_series_column",
    "score_wide_observations",
    "score_wide_time_columns",
    # Time axis interpretation
    "GranularityResult",
    "ParsedTimeHeader",
    "SeriesFrequencyResult",
    "TimeGranularity",
    "TimeRangeResult",
    "detect_granularity",
    "detect_granularity_from_name",
    "detect_granularity_from_values",
    "extract_time_range",
    "extract_time_ranges",
    "infer_series_frequency",
    "parse_time_header",
    "parse_time_headers",
]
